nihe-northern-ireland-housing-statistics
GSS-Cogs/family-homelessness pull request #49
Opened 2021-03-10 09:13 UTC by santhosh-thangavel

1.Stage - 1 transform is completed
2.Period column is formatted
3.Empty String in “Age’ column is replaced by np.nan
4.“Age” column has a pattern number-number and “(yrs)” suffix removed.
5.OBS and DATAMARKER columns are renamed
6.Empty string in Value column is replaced by np.nan
7.Except for the Value and Age column, all other columns are pathified.
8.Cubes class added
9.TransformTrace is added.

2021-03-10 14:11 UTC, santhosh-thangavel commented
@canwaf   Review my pull request please.

2021-03-10 15:28 UTC, canwaf reviewed
Great job getting to the end product.

There's only one thing missing in the output which is what the values are counting (i.e. homeless households).

There's a lot in this PR review, and we can talk about it over a few days, or use the review reply function. Take a look at all the comments first before you try addressing specific ones, to see how it all fits together. Combining `apply` with f-strings and string indexing, and lambda functions will get you closer to a pythonic ideal.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +scraper.distributions = [x for x in scraper.distributions if hasattr(x, "mediaType")]
A comment explaining why you're bringing in an odf and converting it to excel would be worthwhile.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +xls = pd.ExcelFile(scraper.distributions[0].downloadURL, engine="odf")
You should use the `distribution(latest=True)` instead of indexing the possible distributions, especially since we've designed a dataURL which overrides the selection of the dataset anyways.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +datasetTitle = 'Northern Ireland Housing Statistics 2019-20'
Get this from the json file usin indexing. Also you assign this manually, use it in the tracer, but don't use it in the `add_cube()` method on line 152.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +    if tab_name not in [x.name for x in tabs]:
This doens't need to be in the processing loop. You should check whether Set a is in Set b and if not raise an error.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +    tab = [x for x in tabs if x.name == tab_name][0]
You can subindex this faster by saying `tab = tab[tab_name]`, no need to create a list.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +        ]
One thing I've noticed is you haven't defined what the count is. in each of these it's households presenting as homeless, so that needs to be in an additonal column.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +def left(s, amount):
You should use string indexing instead of these definitions. Getting comfortable with python indexing can only happen with practise. I suggest you rewrite this section (through to the year definition) using instructions at https://www.pythoncentral.io/cutting-and-slicing-strings-in-python/.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +        return 'id/government-year/' + left(date, 4) + '-' + left(date, 2) + right(date, 2)
In the comment above you use something very close to an f-string but end up using concatenation instead. Check out the tutorial on f-strings at https://realpython.com/python-f-strings/.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +df['Period'] =  df["Period"].apply(date_time)
Combining fstrings and string indexing, this can still be a single line.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +df['Age'] = df['Age'].apply(converter)
You don't need to declare the convert and apply it. try using a lambda function here, it will look something like `lambda x: str(x).strip('(yrs)')`

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +cubes.add_cube(scraper, df, scraper.title)
The `scraper.title` isn't the same as `datasetTile` which you manually assign on line 26, and use with the tracer on lines 41 and 100. Consistency is key in this case. You could use `scraper.title` in lines 41 and 100 instead of the string assginment.

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +from io import StringIO
Try avoid importing things you don't use. StringIO isn't anywhere here, and you haven't used json either (however you should be using json to pull attributes like the title and family of the dataset)

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +from pandas import ExcelWriter
Instead of importing `ExcelWriter` from pandas you should reference it using the already available `pd.ExcelWriter`

2021-03-10 15:28 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +        remove = tab.filter(contains_string("1. See Appendix 3: Data Sources - Social Renting Demand.")).expand(RIGHT).expand(DOWN)|tab.filter(contains_string('Total'))
This is a good pattern.

2021-03-11 15:49 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +    if tab_name not in [x.name for x in tabs]:
```if set(tabs_to_transform) - set(all tabs) != 0:
   raise ValueError(f"Aborting. A tab named {set(tabs_to_transform) - set(all tabs)} required but not found")
```

2021-03-11 15:53 UTC, canwaf commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +    tab = [x for x in tabs if x.name == tab_name][0]
`tab = tabs[tab_name]`

2021-03-18 15:55 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +from pandas import ExcelWriter
Referenced it as pd.ExcelWriter instead of ExcelWriter

2021-03-18 15:55 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +from io import StringIO
StringIO is removed and unwanted things are removed as well

2021-03-18 15:58 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +scraper.distributions = [x for x in scraper.distributions if hasattr(x, "mediaType")]
Added comment  "The source data is published in ODS format. ODS is converted to xls with the below lines of code as databaker is compatible with xls"

2021-03-18 16:02 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +datasetTitle = 'Northern Ireland Housing Statistics 2019-20'
Added info = json.load(open("info.json")) in the beginning and got datasetTile through datasetTitle = info['title'] and used in add_cube() as well. Manually adding datasetTitle and bringing in title using scraper is avoided.

2021-03-18 16:03 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +        ]
Hardcoded 
unit = "household"

2021-03-18 16:04 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +def left(s, amount):
Used string indexing and f-string to format "Period" column

2021-03-18 16:07 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +        return 'id/government-year/' + left(date, 4) + '-' + left(date, 2) + right(date, 2)
Formatted  "Period column" using f-string and string indexing and slicing.
df['Period'] = df['Period'].cat.rename_categories(lambda x: f"id/government-year/{x[:4]}-{x[:2]}{x[-2:]}")

2021-03-18 16:08 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +df['Period'] =  df["Period"].apply(date_time)
Removed this line as f-string and string indexing has solved the issue.

2021-03-18 16:09 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +df['Age'] = df['Age'].apply(converter)
Used anonymous function instead of a named function.

2021-03-18 16:11 UTC, santhosh-thangavel commented on datasets/NIHE-Northern-Ireland-Housing-Statistics/main.py
> +cubes.add_cube(scraper, df, scraper.title)
Used datasetTitle = info["title"] through out for consistency

2021-03-19 15:41 UTC, canwaf requested changes
Please address all points within comments.

2021-03-25 10:25 UTC, canwaf approved these changes
Good job implementing these changes, and avoiding the use of the for loop when it really didn't save you any work. Look forward to seeing your next dataset.

2021-03-25 11:56 UTC, merged