MHCLG-Statutory-homelessness-Detailed-local-authority-level
GSS-Cogs/family-homelessness pull request #52
Opened 2021-04-19 10:55 UTC by santhosh-thangavel

1. Completed stage-1 transform of the dataset
2. Each tab is transformed separately

2021-04-19 11:02 UTC, santhosh-thangavel commented
#52 @canwaf Please, Can you review my pull request?

2021-04-20 15:15 UTC, canwaf requested changes
You haven't finished this transform, adding the data to the cube, etc. Before you do any work on improving the process, where there are some good habits and bad in here, export the data frame this generates as an excel file and consider whether it looks like it's ready to be a CSV-W. If not, that might help you identify more work to do.

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +original_tabs = scraper.distribution(title = lambda x: "Detailed local authority level tables: July to September 2020 (revised)" in x)
This line makes it a one-time transform. How can you change this so it will always get the most recent publication?

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +    if tab.name in ['A1']: #only transforming tab A1 for now
You repeat this pattern throughout, You can save line 46, 49 several times over with a statement like `with tabs['A1'] as tab` if you created a dictionary of {tab name: tab} on line 38.

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +        temp_assessment_duty_type_1 = tab.excel_ref('C3').expand(RIGHT)
Can you think of a way to avoid using absolute cell references? Have you tried searching for text?

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +df['Initial Circumstance Assessment'] = df['assessment_duty_type'].map(lambda x: 'Total Initial Assessments' if 'Total initial assessments1' in x
Use a dictionary to map this, it will be easier to read.

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +        trace.store("combined_dataframe", tidy_sheet.topandas())
Don't use this function to create a pandas data frame, since we can't strip out the trace in one go.

```
df = tidy_sheet.topandas()
trace.store("comebined_dataframe", df)
```

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +df
Don't return values in final outputs since they consume compute but don't go anywhere, same goes for returning the distro or scraper.

2021-04-20 15:15 UTC, canwaf commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +df.rename(columns={'OBS' : 'Value', 'DATAMARKER' : 'Marker'}, inplace=True)
Your data frame tailoring needs to be done at the end all at once if you're combining the data frame. YOu're doing a lot of work over and over and over and over and over again when you can just do it one time at the end if the columns align.

2021-04-29 08:52 UTC, santhosh-thangavel commented on datasets/MHCLG-Statutory-homelessness-Detailed-local-authority-level/main.py
> +    if tab.name in ['A1']: #only transforming tab A1 for now
@canwaf Please, can you refer me to any transform with the below pattern?
# For tab when each tab is different
# (e.g. bulletins)
with tabs['Select This'] as tab:
    cubes.add_cube(scraper, tabdf, csvName)
    return
 
with tabs['Select That'] as tab:
    cubes.add_cube(scraper, tabdf, csvName)

2021-06-28 13:16 UTC, santhosh-thangavel commented
@canwaf @Shannon95 The work has been passed over to Shannon. Thank you.

2022-10-17 08:30 UTC, closed without merging